/**
 * Automatic private key generation and persistence for zero-friction MCP server usage.
 *
 * When AZETH_PRIVATE_KEY is not set in the environment, this module:
 * 1. Checks ~/.azeth/key for a persisted key
 * 2. If found, loads and validates it
 * 3. If not found, generates a new key and persists it
 * 4. Sets process.env['AZETH_PRIVATE_KEY'] so all downstream code works unchanged
 *
 * File permissions: ~/.azeth/ = 0o700, ~/.azeth/key = 0o600
 * The private key is NEVER logged — only the derived EOA address.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';

const KEY_FILE_RE = /^0x[0-9a-fA-F]{64}$/;

let _autoGenerated = false;

function log(msg: string): void {
  process.stderr.write(`[azeth-mcp] ${msg}\n`);
}

/** Returns true if the current session's key was loaded from ~/.azeth/key or freshly generated (not from env). */
export function wasAutoGenerated(): boolean {
  return _autoGenerated;
}

/**
 * Ensure AZETH_PRIVATE_KEY is set in the environment.
 * If not set, attempt to load from ~/.azeth/key or generate a new one.
 * Call this once at startup before creating the MCP server.
 */
export function ensurePrivateKey(): void {
  if (process.env['AZETH_PRIVATE_KEY']) return;

  const home = homedir();
  if (!home) {
    generateInMemoryKey('Could not determine home directory — key will not be persisted.');
    return;
  }

  const azethDir = join(home, '.azeth');
  const keyFile = join(azethDir, 'key');

  // Try loading an existing key
  if (existsSync(keyFile)) {
    try {
      const key = readFileSync(keyFile, 'utf-8').trim();
      if (KEY_FILE_RE.test(key)) {
        process.env['AZETH_PRIVATE_KEY'] = key;
        _autoGenerated = true;
        const address = privateKeyToAccount(key as `0x${string}`).address;
        log(`Loaded private key from ~/.azeth/key`);
        log(`EOA address: ${address}`);
        return;
      }
      log('WARNING: ~/.azeth/key contains invalid key. Regenerating.');
    } catch (err) {
      log(`WARNING: Could not read ~/.azeth/key: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // Ensure ~/.azeth/ directory exists and is a directory
  if (existsSync(azethDir)) {
    try {
      if (!statSync(azethDir).isDirectory()) {
        generateInMemoryKey('~/.azeth exists but is not a directory — key will not be persisted.');
        return;
      }
    } catch {
      generateInMemoryKey('Could not stat ~/.azeth — key will not be persisted.');
      return;
    }
  } else {
    try {
      mkdirSync(azethDir, { recursive: true, mode: 0o700 });
    } catch (err) {
      generateInMemoryKey(`Could not create ~/.azeth directory: ${err instanceof Error ? err.message : String(err)}`);
      return;
    }
  }

  // Generate and persist a new key
  const newKey = generatePrivateKey();
  try {
    writeFileSync(keyFile, newKey, { mode: 0o600 });
    // Ensure permissions are correct even if umask interfered
    chmodSync(keyFile, 0o600);
  } catch (err) {
    // Persistence failed — use the key in-memory only
    process.env['AZETH_PRIVATE_KEY'] = newKey;
    _autoGenerated = true;
    const address = privateKeyToAccount(newKey).address;
    log(`Generated new private key (in-memory only — could not write ~/.azeth/key: ${err instanceof Error ? err.message : String(err)})`);
    log(`EOA address: ${address}`);
    log('WARNING: This key will be lost when the MCP server restarts.');
    return;
  }

  process.env['AZETH_PRIVATE_KEY'] = newKey;
  _autoGenerated = true;
  const address = privateKeyToAccount(newKey).address;
  log('Generated new private key and saved to ~/.azeth/key');
  log(`EOA address: ${address}`);
  log('WARNING: This is an auto-generated demo key. For production, set AZETH_PRIVATE_KEY in your environment.');
}

/** Fallback: generate an in-memory-only key when filesystem operations fail */
function generateInMemoryKey(reason: string): void {
  log(`WARNING: ${reason}`);
  const key = generatePrivateKey();
  process.env['AZETH_PRIVATE_KEY'] = key;
  _autoGenerated = true;
  const address = privateKeyToAccount(key).address;
  log(`Generated ephemeral private key (in-memory only)`);
  log(`EOA address: ${address}`);
  log('WARNING: This key will be lost when the MCP server restarts. Set AZETH_PRIVATE_KEY for persistence.');
}
